### PR TITLE
Dev/v0.16.0

### LINKED ISSUE #97: raxoft's `z80test` undocumented opcodes/flags tests fail
There are a lot of failures in z80 tests by @raxoft https://github.com/raxoft/z80test
(Found via https://viva-games.ru/game/zilog-z80-cpu-test-suite)

Passing test tapes: `z80doc.tap` `z80docflags.tap`
Failing test tapes: `z80full.tap`, `z80ccf.tap`, `z80flags.tap`, `z80memptr.tap`

Most likely `ccf` and `memptr` tests fail because lack of `Q` and `Memptr` hidden undocumented registers emulation.

### PR DESCRIPTION
**Pull request by pacmancoder**
### Scope of changes
- [x] Implement Q reg
- [x] Fix memptr implementation
- [x] Implement bizzare block instruction flags
- [x] Tests for all implemented functionality
- [x] Replace zexall, with [z80test](https://github.com/raxoft/z80test) and extend with z80ccf, z80memptr 
- [x] Add block instruction test based on https://github.com/MrKWatkins/ZXSpectrumNextTests/tree/develop/Tests/ZX48_ZX128/Z80BlockInstructionFlags
- [x] Fix invalid sound format discovery (e.g. on Logitech PRO X Gaming Headset)
- [x] Fixed shitload of typos

Closes #97

### CODE REVIEW

File: rustzx-z80/src/opcode/group_nonprefixed.rs [hunk 1]
```diff
@@ -367,6 +371,7 @@ pub fn execute_normal(cpu: &mut Z80, bus: &mut impl Z80Bus, opcode: Opcode, pref
                     flags |= carry as u8 * FLAG_CARRY;
                     flags |= F3F5_TABLE[data as usize];
                     cpu.regs.set_flags(flags);
+                    cpu.regs.set_q(flags);
```
Comment (pacmancoder) [inline rustzx-z80/src/opcode/group_nonprefixed.rs:374]: TODO: Move to `set_flags` and make separate method for settings flags without q if needed
